spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/quiz}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:quiz}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:quiz}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=false
