spring.application.name=kanban-api

server.port=8081

logging.file.name=../logs/kanban-api.log

spring.datasource.mode=json
spring.config.import=optional:classpath:application-${spring.datasource.mode}.properties
