spring.datasource.mode=h2

spring.datasource.url=jdbc:h2:file:./data/kanbandb;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.h2.console.enabled=true

spring.sql.init.mode=never
spring.sql.init.data-locations=classpath:db/agile-schema.sql
spring.sql.init.continue-on-error=false
spring.jpa.defer-datasource-initialization=true
